import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: "auto",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 35,
  },
  topHomeContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  button: {
    display: "flex",
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 5,
    borderWidth: 1.5,
    padding: 10,
    fontSize: 14,
    width: 175,
    alignItems: "center",
    backgroundColor: "skyblue",
    marginHorizontal: 3,
  },
  createListMain: {
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 5,
    height: 440,
    width: "100%",
    marginVertical: 15,
    alignItems: "center",
  },
  listTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 6,
  },
  listTitleText: {
    fontSize: 23,
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  editTitleButton: { marginLeft: 10 },
  editTitleIcon: { height: 18, width: 18 },
  listBodyContainer: {
    width: "90%",
    height: 160,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "black",
    alignItems: "center",
    justifyContent: "center",
  },
  listEntry: {
    height: 50,
    width: "85%",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "black",
    textAlign: "center",
    marginBottom: 20,
    fontSize: 18,
  },
  listEntryButton: {
    width: "85%",
  },
  listEntryButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 18,
  },
  width90: { width: "90%" },
  listPreviewText: {
    marginTop: 10,
    fontSize: 25,
  },
  submitBtnExtra: { width: "100%", marginHorizontal: 0 },
  centerAlign: { alignItems: "center" },
  welcomeTitle: {
    fontSize: 50,
    fontWeight: "bold",
    color: "skyblue",
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 30,
    color: "skyblue",
    textAlign: "center",
  },
});
